sudo: required
services:
    - docker

before_install:
    - docker build -t nikoladragas/react-test -f ./client/Dockerfile.dev ./client
    #Build tests for other projects

script:
    - docker run nikoladragas/react-test npm test -- --coverage
    #Run those other tests

after_success:
    - docker build -t nikoladragas/multi-client ./client
    - docker build -t nikoladragas/multi-nginx ./nginx
    - docker build -t nikoladragas/multi-server ./server
    - docker build -t nikoladragas/multi-worker ./worker
    #Login to the docke CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push nikoladragas/multi-client
    - docker push nikoladragas/multi-nginx 
    - docker push nikoladragas/multi-server
    - docker push nikoladragas/multi-worker